const SET_GOOGLE_API_USER_INFO = "SET_GOOGLE_API_USER_INFO",
      SET_GOOGLE_DRIVE_FILES   = "SET_GOOGLE_DRIVE_FILES",
      SET_WEBSOCKET            = "SET_WEBSOCKET"

export {
    SET_GOOGLE_API_USER_INFO,
    SET_GOOGLE_DRIVE_FILES,
    SET_WEBSOCKET
}