name: Fiesta_Frontend_CI

on:
  push:
    branches: [fiesta]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build jitsi-meet frontend for Fiesta
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Deploy to the main host
#       uses: fifsky/ssh-action@master
#       with:
#         command: |
#             cd ~/house.fiesta.app/web/trs-jitsi-meet
#             npm install
#         host: ${{ secrets.FIESTA_MEET_MAIN_SERVER }}
#         user: ubuntu
#         key: ${{ secrets.FIESTA_PRIVKEY }}