name: Fiesta_Frontend_CI

on:
  push:
    branches: [fiesta]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to the main host
      uses: fifsky/ssh-action@master
      with:
        command: |
            cd ~/house.fiesta.app/web/trs-jitsi-meet
            sudo npm install -g npm@latest
            cd ~/house.fiesta.app/web/trs-jitsi-meet/
            npm install
        host: ${{ secrets.FIESTA_MEET_MAIN_SERVER }}
        user: ubuntu
        key: ${{ secrets.FIESTA_PRIVKEY }}